### ISSUE TITLE
Does not Compile on WSL Ubuntu

### ISSUE THREAD

**Issue by wyatt-herkamp** [alfredosa/to-redo#1]
```
error: failed to run custom build command for `ncurses v5.101.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installFuFrdW/release/build/ncurses-771a6519050043a9/build-script-build` (exit status: 101)
  --- stdout
{A BUNCH OF FLAGS}
  --- stderr
  /tmp/cargo-installFuFrdW/release/build/ncurses-9575f64412318c00/out/chtype_size.c:6:10: fatal error: ncurses.h: No such file or directory
      6 | #include <ncurses.h>
        |          ^~~~~~~~~~~
  compilation terminated.
  thread 'main' panicked at /home/wherkamp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ncurses-5.101.0/build.rs:105:5:
  assertion failed: command.status().expect(\"compilation failed\").success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `bashtastic-visualizer v0.1.5`, intermediate artifacts can be found at `/tmp/cargo-installFuFrdW`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
I am guessing it is related to https://github.com/jeaye/ncurses-rs/issues/213

If you know how to fix this let me know.

You might want to consider moving to [RUI](https://github.com/ratatui-org/ratatui) as it is has more maintenance.

**Comment by alfredosa** [comment]
Hey @wyatt-herkamp!! Yeah, you have to fully install ncurses if it's not in your ubuntu, I think you can:

```bash
sudo apt-get update
sudo apt-get install libncurses-dev
```
Let me know, super cool you are testing it out :)

**Comment by wyatt-herkamp** [comment]
> Hey @wyatt-herkamp!! Yeah, you have to fully install ncurses if it's not in your ubuntu, I think you can:
> 
> ```shell
> sudo apt-get update
> sudo apt-get install libncurses-dev
> ```
> 
> Let me know, super cool you are testing it out :)

Yep that was the library you might want to add a note in your readme.
